// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission.Data;

#nullable disable

namespace Mission.Migrations
{
    [DbContext(typeof(MissionDbContext))]
    [Migration("20261008202145_addingwhatever")]
    partial class addingwhatever
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mission.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Titre = "Vélos"
                        },
                        new
                        {
                            Id = 2,
                            Titre = "Composantes"
                        },
                        new
                        {
                            Id = 3,
                            Titre = "Vêtements"
                        },
                        new
                        {
                            Id = 4,
                            Titre = "Accessoires"
                        });
                });

            modelBuilder.Entity("Mission.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 3,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8698),
                            Description = "Long-Sleeve Logo Jersey, S",
                            PrixVente = 38m
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 3,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8725),
                            Description = "Long-Sleeve Logo Jersey, M",
                            PrixVente = 38m
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8741),
                            Description = "HL Road Frame - Red, 62",
                            PrixVente = 868m
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8755),
                            Description = "HL Road Frame - Red, 44",
                            PrixVente = 870m
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8770),
                            Description = "LL Road Frame - Red, 44",
                            PrixVente = 870m
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8788),
                            Description = "Road-150 Red, 62",
                            PrixVente = 2171m
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8804),
                            Description = "Road-150 Red, 44",
                            PrixVente = 2171m
                        },
                        new
                        {
                            Id = 8,
                            CategorieId = 4,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8819),
                            Description = "LL Headset",
                            PrixVente = 16m
                        },
                        new
                        {
                            Id = 9,
                            CategorieId = 2,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8833),
                            Description = "LL Mountain Handlebars",
                            PrixVente = 19m
                        },
                        new
                        {
                            Id = 10,
                            CategorieId = 2,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8850),
                            Description = "LL Mountain Front Wheel",
                            PrixVente = 27m
                        },
                        new
                        {
                            Id = 11,
                            CategorieId = 3,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8865),
                            Description = "Classic Vest, M",
                            PrixVente = 24m
                        },
                        new
                        {
                            Id = 12,
                            CategorieId = 4,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8880),
                            Description = "ML Road Seat/Saddle",
                            PrixVente = 50m
                        },
                        new
                        {
                            Id = 13,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8894),
                            Description = "Mountain-500 Silver, 40",
                            PrixVente = 308m
                        },
                        new
                        {
                            Id = 14,
                            CategorieId = 1,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8909),
                            Description = "Mountain-500 Silver, 42",
                            PrixVente = 308m
                        },
                        new
                        {
                            Id = 15,
                            CategorieId = 4,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8924),
                            Description = "LL Bottom Bracket",
                            PrixVente = 22m
                        },
                        new
                        {
                            Id = 16,
                            CategorieId = 4,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8939),
                            Description = "ML Bottom Bracket",
                            PrixVente = 22m
                        },
                        new
                        {
                            Id = 17,
                            CategorieId = 2,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8953),
                            Description = "Rear Brakes",
                            PrixVente = 47m
                        },
                        new
                        {
                            Id = 18,
                            CategorieId = 3,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8969),
                            Description = "Racing Socks, M",
                            PrixVente = 4m
                        },
                        new
                        {
                            Id = 19,
                            CategorieId = 3,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8984),
                            Description = "Racing Socks, L",
                            PrixVente = 4m
                        },
                        new
                        {
                            Id = 20,
                            CategorieId = 4,
                            DateCreation = new DateTime(2026, 10, 8, 16, 21, 44, 496, DateTimeKind.Local).AddTicks(8999),
                            Description = "Hydration Pack - 70 oz.",
                            PrixVente = 21m
                        });
                });

            modelBuilder.Entity("Mission.Models.Produit", b =>
                {
                    b.HasOne("Mission.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Mission.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
